var set = [ 'juk_dum',
			'juk_dum',
			'juk_dum',
			'juk_dum',
			'juk_dum',
			'juk_dang',
			'juk_dang',
			'juk_dang',
			'juk_dang',
			'juk_dang', 
			'pao_dum',
			'pao_dum',
			'pao_dang',
			'pao_dang',
			'ma_dum',
			'ma_dum',
			'ma_dang',
			'ma_dang',
			'ship_dum',
			'ship_dum',
			'ship_dang',
			'ship_dang',
			'chang_dum',
			'chang_dum',
			'chang_dang',
			'chang_dang',
			'bin_dum',
			'bin_dum',
			'bin_dang',
			'bin_dang',
			'tee_dum',
			'tee_dang' ];

var test = [ 'juk_dum',
			'juk_dum',
			'juk_dum',
			'juk_dum',
			'juk_dum',
			'juk_dang',
			'juk_dang',
			'juk_dang',
			'juk_dang',
			'juk_dang', 
			'pao_dum',
			'pao_dum',
			'pao_dang',
			'pao_dang',
			'ma_dum',
			'ma_dum',
			'ma_dang',
			'ma_dang',
			'ship_dum',
			'ship_dum',
			'ship_dang',
			'ship_dang',
			'chang_dum',
			'chang_dum',
			'chang_dang',
			'chang_dang',
			'bin_dum',
			'bin_dum',
			'bin_dang',
			'bin_dang',
			'tee_dum',
			'tee_dang' ];		

var one = [ 'juk_dum' , 
			'juk_dang' , 
			'pao_dum' , 
			'pao_dang' , 
			'ma_dum' , 
			'ma_dang' , 
			'ship_dum' , 
			'ship_dang' , 
			'chang_dum' , 
			'chang_dang' , 
			'bin_dum' , 
			'bin_dang' , 
			'tee_dum' , 
			'tee_dang' ];

var tuy = [ ['juk_dum' , 'juk_dum'] , 
			['juk_dang' , 'juk_dang'] , 
			['pao_dum' , 'pao_dum'] , 
			['pao_dang' , 'pao_dang'] , 
			['ma_dum' , 'ma_dum'] , 
			['ma_dang' , 'ma_dang'] , 
			['ship_dum' , 'ship_dum'] , 
			['ship_dang' , 'ship_dang'] , 
			['chang_dum' , 'chang_dum'] , 
			['chang_dang' , 'chang_dang'] , 
			['bin_dum' , 'bin_dum'] , 
			['bin_dang' , 'bin_dang'] ];

var hu = [ ['pao_dum' , 'ma_dum' , 'ship_dum'].sort() , 
	  	   ['pao_dang' , 'ma_dang' , 'ship_dang'].sort() , 
	   	   ['tee_dum' , 'bin_dum' , 'chang_dum'].sort() , 
	       ['tee_dang' , 'bin_dang' , 'chang_dang'].sort() ];

var hu4 = [ ['pao_dum' , 'pao_dum' , 'ma_dum' , 'ship_dum'].sort() , 
	    	['pao_dum' , 'ma_dum' , 'ma_dum' , 'ship_dum'].sort() , 
	    	['pao_dum' , 'ship_dum' , 'ma_dum' , 'ship_dum'].sort() , 
	    	['pao_dang' , 'pao_dang' , 'ma_dang' , 'ship_dang'].sort() , 
	    	['ma_dang' , 'pao_dang' , 'ma_dang' , 'ship_dang'].sort() , 
	    	['pao_dang' , 'ma_dang' , 'ship_dang' , 'ship_dang'].sort() , 
	    	['tee_dum' , 'bin_dum' , 'chang_dum' , 'chang_dum'].sort() , 
	    	['tee_dum' , 'bin_dum' , 'bin_dum' , 'chang_dum'].sort() , 
	    	['tee_dang' , 'bin_dang' , 'chang_dang' , 'chang_dang'].sort() , 
	    	['tee_dang' , 'bin_dang' , 'bin_dang' , 'chang_dang'].sort() ];

var hu5 = [ ['pao_dum' , 'pao_dum' , 'ma_dum' , 'ma_dum' , 'ship_dum'].sort() ,
			['pao_dum' , 'pao_dum' , 'ma_dum' , 'ship_dum' , 'ship_dum'].sort() ,
			['pao_dum' , 'ma_dum' , 'ma_dum' , 'ship_dum' , 'ship_dum'].sort() , 
			['pao_dang' , 'pao_dang' , 'ma_dang' , 'ma_dang' , 'ship_dang'].sort() ,
			['pao_dang' , 'pao_dang' , 'ma_dang' , 'ship_dang' , 'ship_dang'].sort() ,
			['pao_dang' , 'ma_dang' , 'ma_dang' , 'ship_dang' , 'ship_dang'].sort() , 
			['tee_dum' , 'bin_dum' , 'bin_dum' , 'chang_dum' , 'chang_dum' ].sort()  ,
			['tee_dang' , 'bin_dang' , 'bin_dang' , 'chang_dang' , 'chang_dang' ].sort() ];

var hu6 = [ ['pao_dum' , 'pao_dum' , 'ma_dum' , 'ma_dum' , 'ship_dum' , 'ship_dum'].sort() ,
			['pao_dang' , 'pao_dang' , 'ma_dang' , 'ma_dang' , 'ship_dang' , 'ship_dang'].sort() ];